// Thumbnail mapping for press articles
// This file contains the mapping of article titles to their thumbnail URLs
// Extracted from https://rocketfuel.inc/press-coverage/

export const thumbnailMapping: Record<string, string> = {
    "RocketFuel Pre-Announces Record Growth In Q1-Q3 2024": "https://rocketfuel.inc/wp-content/uploads/2025/01/Screenshot-2025-01-06-at-5.14.05%E2%80%AFPM-1024x414.png",
    "RocketFuel CEO shares vision of transforming payments": "https://rocketfuel.inc/wp-content/uploads/2024/05/Screenshot-2024-05-16-at-9.43.03%E2%80%AFPM-1024x518.png",
    "RocketFuel CEO sees stablecoin adoption transforming B2B transactions": "https://rocketfuel.inc/wp-content/uploads/2024/04/Screenshot-2024-04-26-at-12.06.24%E2%80%AFAM-1024x563.png",
    "RocketFuel CEO sees Bitcoin surge driving crypto awareness and adoption": "https://rocketfuel.inc/wp-content/uploads/2024/04/Screenshot-2024-04-25-at-2.35.44%E2%80%AFPM-1024x565.png",
    "Stablecoins attractive amid lack of clarity on crypto regulations, RocketFuel CEO says": "https://rocketfuel.inc/wp-content/uploads/2024/04/Screenshot-2024-04-25-at-2.49.02%E2%80%AFPM-1024x566.png",
    "RocketFuel Blockchain pre-announces impressive 3Q revenue growth": "https://rocketfuel.inc/wp-content/uploads/2024/02/Screenshot-2024-02-22-at-1.08.07%E2%80%AFPM-1024x665.png",
    "RocketFuel exec: \"2024 seems like a great place to be in the crypto market\"": "https://rocketfuel.inc/wp-content/uploads/2024/02/Screenshot-2024-02-22-at-1.13.10%E2%80%AFPM-1024x665.png",
    "RocketFuel it’s hardly surprising": "https://rocketfuel.inc/wp-content/uploads/2023/12/CRYPTO-_-%E2%80%93-Payout-Magazine-1024x508.jpg",
    "RocketFuel is optimizing how businesses move money with crypto transactions topping 400,000 in the year to date": "https://rocketfuel.inc/wp-content/uploads/2023/12/RocketFuel-is-optimizing-how-businesses-move-money-with-crypto-transactions-topping-400-000-in-the-year-to-date-OTCQB-RKFL-1024x508.jpg",
    "RocketFuel says “sky’s the limit” as it prepares for more growth": "https://rocketfuel.inc/wp-content/uploads/2023/12/RocketFuel-says-sky-s-the-limit-as-it-prepares-for-more-growth-OTCQB-RKFL-1024x514.jpg",
    "RocketFuel says crypto is revolutionizing global payments for businesses": "https://rocketfuel.inc/wp-content/uploads/2023/12/RocketFuel-says-crypto-is-revolutionizing-global-payments-for-businesses-OTCQB-RKFL-1024x514.jpg",
    "RocketFuel teams up with Ripple to simplify cross border payments": "https://rocketfuel.inc/wp-content/uploads/2023/12/RocketFuel-teams-up-with-Ripple-to-simplify-cross-border-payments-OTCQB-RKFL-1024x514.jpg",
    "RocketFuel says crypto payments are overcoming obstacles for large multinationals": "https://rocketfuel.inc/wp-content/uploads/2023/09/Screenshot-2023-09-05-at-3.57.30-PM-1024x594.png",
    "AI and Blockchain Technology Combined: RocketFuel's Ben Yankowitz": "https://rocketfuel.inc/wp-content/uploads/2023/08/Screenshot-2023-08-24-at-10.52.57-AM-1024x569.png",
    "Cryptocurrency's surge in Latin America: A Q&A with RocketFuel's Monica Taher": "https://rocketfuel.inc/wp-content/uploads/2023/08/Screenshot-2023-08-23-at-11.33.23-AM-1024x512.png",
    "PayPal exploring untapped stablecoin market, analysts say as launch of PYUSD generates excitement": "https://rocketfuel.inc/wp-content/uploads/2023/08/Screenshot-2023-08-23-at-11.42.35-AM-1024x558.png",
    "RocketFuel Blockchain set to achieve positive cash flow in September as transactions soar on new products and customer wins": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-26-at-11.26.59-AM-1024x565.png",
    "RocketFuel Blockchain set to achieve positive cash flow in September": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-26-at-11.26.59-AM-1024x565.png", // Alias for the above
    "RocketFuel Announces 15x Increase in Customer Traction from New Products and Customers": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-26-at-11.21.18-AM-1024x823.png",
    "RocketFuel Announces 15x Increase in Customer Traction from New Products": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-26-at-11.21.18-AM-1024x823.png", // Alias
    "RocketFuel and Poncho Brotherz collaborate to enable cryptocurrency payments at cannabis dispensary": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-18-at-9.26.07-AM-1024x576.png",
    "RocketFuel CEO says BlackRock’s proposed spot Bitcoin ETF could be watershed moment for crypto": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-12-at-10.57.10-AM-1024x635.png",
    "RocketFuel CEO says BlackRock's proposed spot Bitcoin ETF could be watershed moment": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-12-at-10.57.10-AM-1024x635.png", // Alias
    "RocketFuel is revolutionizing online payments with cryptocurrencies and seamless checkout experience": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-12-at-10.54.39-AM-1024x460.png",
    "RocketFuel is revolutionizing online payments with cryptocurrencies": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-12-at-10.54.39-AM-1024x460.png", // Alias
    "RocketFuel weighs in on how Bitcoin ETF approval can encourage crypto adoption and awareness": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-12-at-10.49.33-AM-1024x462.png",
    "RocketFuel weighs in on how Bitcoin ETF approval can encourage crypto adoption": "https://rocketfuel.inc/wp-content/uploads/2023/07/Screenshot-2023-07-12-at-10.49.33-AM-1024x462.png", // Alias
    "RocketFuel has a winner in B2B Cross-Border Payments, leveraging blockchain to cut costs": "https://rocketfuel.inc/wp-content/uploads/2023/07/RocketFuel-has-a-winner-in-B2B-Cross-Border-Payments-leveraging-blockchain-to-cut-costs-OTCMKTS-RKFL-1024x521.jpg",
    "RocketFuel stock flies after it raises revenue guidance to $5 million": "https://rocketfuel.inc/wp-content/uploads/2023/06/RocketFuel-Blockchain-Inc-flies-rockets-after-it-raises-revenue-guidance-to-5-million-1024x521.jpg",
    "Rocketfuel Blockchain Inc (OTCMKTS: RKFL) On the Move as Blockchain Based Global Payments Solution Gains Traction": "https://rocketfuel.inc/wp-content/uploads/2023/06/Rocketfuel-Blockchain-Inc-OTCMKTS-RKFL-On-the-Move-as-Blockchain-Based-Global-Payments-Solution-Gains-Traction-Newsy-Trends-1024x517.jpg",
    "RocketFuel CEO shares the power of blockchain technology beyond SEC lawsuits on crypto exchanges": "https://rocketfuel.inc/wp-content/uploads/2023/06/RocketFuel-CEO-shares-the-power-of-blockchain-technology-beyond-SEC-lawsuits-on-crypto-exchanges-1024x486.jpg",
    "RocketFuel exec to shine spotlight on blockchain technology at European summit": "https://rocketfuel.inc/wp-content/uploads/2023/06/RocketFuel-exec-to-shine-spotlight-on-blockchain-technology-at-upcoming-European-summit-1024x491.jpg",
    "RocketFuel launches Payouts product to let businesses pay customers in crypto": "https://rocketfuel.inc/wp-content/uploads/2023/06/RocketFuel-Inc-launches-its-Payouts-product-to-let-businesses-pay-their-customers-in-crypto-1024x491.jpg",
    "RocketFuel Blockchain launches Payouts program for users to receive crypto and fiat worldwide": "https://rocketfuel.inc/wp-content/uploads/2023/06/RocketFuel-Blockchain-launches-Payouts-program-for-users-to-receive-crypto-and-fiat-worldwide-Barron-s-1024x517.jpg",
    "As Legacy Payment Companies Lag Behind in Blockchain Adoption, What Will Keep Them Competitive in Web3?": "https://rocketfuel.inc/wp-content/uploads/2023/06/As-Legacy-Payment-Companies-Lag-Behind-in-Blockchain-Adoption-What-Will-Keep-Them-Competitive-in-Web3-MarketScale-1024x521.jpg",
    "Digital Future Society Summit at Barcelona’s Mobile Congress (Spanish)": "https://rocketfuel.inc/wp-content/uploads/2023/06/%C2%BFComo-mejorar-el-impacto-de-la-tecnologia-en-la-sociedad-Los-expertos-hablan-1024x486.jpg",
    "CEO de RocketFuel: “Los governments no permitirán las criptomonedas sin involucrarse”": "https://rocketfuel.inc/wp-content/uploads/2023/06/CEO-de-RocketFuel-Los-gobiernos-no-permitiran-las-criptomonedas-sin-involucrarse-1024x521.jpg",
    "Mónica Taher, RocketFuel’s VP of Marketing, Leadership in Bitcoin (Spanish)": "https://rocketfuel.inc/wp-content/uploads/2023/06/Monica-Taher-inversionista-e-influencia-en-Bitcoin-1024x491.jpg",
    "Mónica Taher, RocketFuel’s VP of Marketing, Chosen as One of the Most Influential Leaders in the Crypto Ecosystem in Latinamerica (Spanish)": "https://rocketfuel.inc/wp-content/uploads/2023/06/Quienes-son-las-personas-mas-influuyente-cripto-en-Latam-1024x491.jpg",
    "RocketFuel Blockchain Debuts B2B Cross-Border Settlement Solution": "https://rocketfuel.inc/wp-content/uploads/2023/06/Today-in-B2B-Payments-Back-Office-Operations-Deserve-More-CFO-Attention-RocketFuel-Blockchain-Debuts-B2B-Cross-Border-Settlement-Solution-1024x491.jpg",
    "5 Key Trends Noted at NRF 2022: Retail’s Big Show": "https://rocketfuel.inc/wp-content/uploads/2023/06/5-Key-Trends-Noted-at-NRF-2022-Retails-Big-Show-Progressive-Grocer-1024x486.jpg",
    "Bitcoin Headed for its Worst Week in Six Months": "https://rocketfuel.inc/wp-content/uploads/2023/06/Bitcoin-headed-for-its-worst-week-in-six-months-Fox-Business-1024x517.jpg",
    "Crypto Creeps into the Checkout Line: Payments Firms are Betting on Crypto’s Growth as an Asset Class": "https://rocketfuel.inc/wp-content/uploads/2023/06/Crypto-creeps-into-the-checkout-line-Banking-Dive-1024x521.jpg",
    "Crypto Creeps into the Checkout Line": "https://rocketfuel.inc/wp-content/uploads/2023/06/Crypto-creeps-into-the-checkout-line-Banking-Dive-1024x521.jpg", // Alias
    "ACI Teams With RocketFuel To Power Cryptocurrency Merchant Payments": "https://rocketfuel.inc/wp-content/uploads/2023/06/ACI-Teams-With-RocketFuel-To-Power-Cryptocurrency-Merchant-Payments-1024x491.jpg",
    "The first Bitcoin-linked ETF is here: What to know about crypto funds before you invest": "https://rocketfuel.inc/wp-content/uploads/2023/06/Bitcoin-ETFs-What-Are-They-Bankrate-1024x486.jpg",
    "Coinseed Shutdown: What are the Lessons to be Learned by Cryptocurrency Traders?": "https://rocketfuel.inc/wp-content/uploads/2023/06/Coinseed-shutdown-what-are-the-lessons-to-be-learned-by-crypto-traders--1024x491.jpg",
    "The Fed May Release its Long-Awaited Paper on Central Bank Digital Currencies as Early as Next Week, Report Says": "https://rocketfuel.inc/wp-content/uploads/2023/06/Fed-s-Paper-on-Digital-Currencies-May-Be-Out-Next-Week-1024x517.jpg",
    "Crypto marketplace sent $90 million to users, thanks to a bug. Now it wants the money back.": "https://rocketfuel.inc/wp-content/uploads/2023/06/Crypto-marketplace-sent-90-million-to-users-thanks-to-a-bug-Now-it-wants-the-money-back-CBS-News-1024x517.jpg",
    "RocketFuel Makes Crypto One-Click Pay Available For Cannabis Industry": "https://rocketfuel.inc/wp-content/uploads/2023/06/Bitcoin-Daily-RocketFuel-Makes-Crypto-One-Click-Pay-Available-For-Cannabis-Industry-Tesla-Retains-Its-1-3B-Bitcoin-Investment-1024x491.jpg",
    "The Case for Cryptocurrencies as the Future of Digital Payments": "https://rocketfuel.inc/wp-content/uploads/2023/06/COMMENTARY-The-Case-for-Cryptocurrencies-As-the-Future-of-Digital-Payments-%E2%80%93-Digital-Transactions-1024x521.jpg",
    "Blockchain Company Makes A Potentially Industry-Changing Announcement": "https://rocketfuel.inc/wp-content/uploads/2023/06/Baystreet-ca-Blockchain-Company-Makes-A-Potentially-Industry-Changing-Announcement-1024x486.jpg",
    "Cryptocurrencies are the Future of Payments: Here is How Merchants Fit In": "https://rocketfuel.inc/wp-content/uploads/2023/06/Cryptocurrencies-are-the-Future-of-Payments-Here-is-How-Merchants-Fit-In-Retail-TouchPoints-1024x491.jpg",
    "RocketFuel Introduces Industry-First Price Settlement Guarantee": "https://rocketfuel.inc/wp-content/uploads/2023/06/RocketFuel-Introduces-Industry-First-Price-Settlement-Guarantee-to-Protect-Merchants-from-Crypto-Volatility-1024x517.jpg",
    "RocketFuel Introduces Industry-First “Price Settlement Guarantee” to Protect Merchants from Crypto Volatility": "https://rocketfuel.inc/wp-content/uploads/2023/06/RocketFuel-Introduces-Industry-First-Price-Settlement-Guarantee-to-Protect-Merchants-from-Crypto-Volatility-1024x517.jpg", // Alias
    "The Surge of Young Investors: Shocking Number Entered Market in Past 6 Months": "https://rocketfuel.inc/wp-content/uploads/2023/06/Business-GOBankingRates-1024x517.jpg",
    "Crypto & eCommerce: Can Cryptocurrency Payments Reduce Chargebacks & More?": "https://rocketfuel.inc/wp-content/uploads/2023/06/Crypto-eCommerce-Can-Cryptocurrency-Payments-Reduce-Chargebacks-More-Finance-Magnates-1024x517.jpg",
    "Millennials Own More Crypto Than Any Other Generation": "https://rocketfuel.inc/wp-content/uploads/2023/06/Millennials-Own-More-Crypto-Than-Any-Other-Generation-1024x517.jpg",
    "Bitcoin sinks 8% as crypto market volatility again rears its head": "https://rocketfuel.inc/wp-content/uploads/2023/06/Bitcoin-Price-Drops-As-Volatility-in-the-Cryptocurrency-Market-Returns-1024x517.jpg",
    "Bitcoin rises to reclaim the $40,000 level as the cryptocurrency tries to recover from brutal selloff": "https://rocketfuel.inc/wp-content/uploads/2023/06/Bitcoin-Rises-to-Reclaim-the-40-000-Level-After-a-Brutal-Selloff-1024x486.jpg",
    "Alt Season Ain't Over Yet: Crypto Markets Recover after Shedding Billions": "https://rocketfuel.inc/wp-content/uploads/2023/06/Alt-Season-Aint-Over-Yet-Crypto-Markets-Recover-after-Shedding-Billions-Finance-Magnates-1024x517.jpg",
    "Restaurants' Appetite for Cryptocurrency is Growing": "https://rocketfuel.inc/wp-content/uploads/2023/06/Restaurants-appetite-for-cryptocurrency-is-growing-1024x517.jpg",
    "Restaurants’ Appetite for Cryptocurrency is Growing": "https://rocketfuel.inc/wp-content/uploads/2023/06/Restaurants-appetite-for-cryptocurrency-is-growing-1024x517.jpg", // Alias with smart quote
    "Rocketfuel Blockchain: The key to the future of payments": "https://rocketfuel.inc/wp-content/uploads/2023/06/RocketFuel-Blockchain-The-Key-to-the-Future-of-Payments-The-Coin-Republic-1024x521.jpg",
    "Card Not Present – Startup RocketFuel Aims To Facilitate Crypto Payments For Online Merchants": "https://rocketfuel.inc/wp-content/uploads/2023/06/Startup-Aims-to-Facilitate-Crypto-Payments-for-Online-Merchants-1024x517.jpg",
    "RocketFuel: Payment Checkout Reinvented": "https://rocketfuel.inc/wp-content/uploads/2023/06/ROCKETFUEL-BLOCKCHAIN-payment-checkout-Fintech-News-1024x517.jpg"
};
